'use strict';
const $=id=>document.getElementById(id), clear=n=>n.replaceChildren(), sleep=ms=>new Promise(r=>setTimeout(r,ms));
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
let ws,connecting=false,session=null,profileId='',revision=0,actions=[],page='',group='',availability='',ignition=false,frame=null,frameAt=0,lastMessage=0,retry=null,sequence=0,lastDetails=0;
let panel='mfdSetup',expanded='',menuBusy=false,pitCursor=null,pitTyre=null,pitRepair=null,pitSent=false,syncChoice={row:null,tyre:null,repair:null};
let circuits=new Map(),circuitLoading=false;
const presses=new Map(),gestures=new Map(),acks=new Map();
const uid=()=>Date.now().toString(36)+'-'+(++sequence).toString(36), text=(id,value)=>{$(id).textContent=value;};
const isF1=()=>profileId==='f1-24'||profileId==='f1-25';
const action=id=>actions.find(a=>a.id===id), inputReady=()=>session&&availability==='ready', ready=()=>inputReady()&&!menuBusy;
function send(type,body={}){if(!session||ws?.readyState!==1)return false;ws.send(JSON.stringify({protocolMajor:1,sessionId:session,type,...body}));return true;}
function sendInvoke(a,phase,pressId,commandId=uid()){return send('control.invoke',{commandId,profileId,profileRevision:revision,actionId:a.id||a,phase,pressId});}
function invoke(a,phase='press',pressId=uid()){sendInvoke(a,phase,pressId);}
function invokeAck(id){return new Promise(resolve=>{const a=action(id);if(!a){resolve(false);return;}const commandId=uid(),pressId=uid();const timer=setTimeout(()=>{acks.delete(commandId);resolve(false);},1500);acks.set(commandId,{resolve:v=>{clearTimeout(timer);resolve(v);}});if(!sendInvoke(a,'press',pressId,commandId)){clearTimeout(timer);acks.delete(commandId);resolve(false);}});}
function resetPit(){pitCursor=pitTyre=pitRepair=null;pitSent=false;}
function release(){send('input.releaseAll');presses.clear();gestures.clear();for(const w of acks.values())w.resolve(false);acks.clear();menuBusy=false;document.querySelectorAll('.down').forEach(b=>b.classList.remove('down'));}
function stop(){clearTimeout(retry);release();session=null;availability='';if(ws){const old=ws;ws=null;old.close();}renderLive();}
async function loadCircuits(){if(circuitLoading||circuits.size)return;circuitLoading=true;try{const r=await fetch('/f1-circuits.json',{cache:'force-cache'}),j=await r.json();circuits=new Map(j.tracks.map(t=>[t.id,t]));renderDetails(true);}catch{circuits=new Map();}finally{circuitLoading=false;}}
async function connect(){
 if(document.hidden||connecting||ws?.readyState===0||ws?.readyState===1)return;connecting=true;clearTimeout(retry);text('connection','Соединение…');
 try{const r=await fetch('/status',{cache:'no-store'});if(r.status===401){$('pairing').hidden=false;$('deck').hidden=true;text('connection','Нужен код с ПК');return;}if(!r.ok)throw Error('HTTP '+r.status);if(document.hidden)return;
 const socket=new WebSocket('ws://'+location.host+'/ws');ws=socket;
 socket.onmessage=e=>{if(ws!==socket)return;try{const m=JSON.parse(e.data);if(m.protocolMajor!==1)throw Error('Версия протокола');lastMessage=performance.now();
  if(m.type==='hello'){session=m.sessionId;profileId=m.profileId;revision=m.profileRevision;actions=m.controls;frame=null;ignition=false;$('pairing').hidden=true;$('deck').hidden=false;text('profile',m.profileName);text('connection','Подключено');page=isF1()?'Control Scheme':actions[0]?.page||'';group='';loadCircuits();renderControls();}
  else if(m.sessionId!==session)throw Error('Сессия изменилась');
  else if(m.type==='telemetry.snapshot'){frame=m;frameAt=performance.now();renderLive();}
  else if(m.type==='input.state'){availability=m.availability;ignition=m.ignitionReady;renderLive();}
  else if(m.type==='control.ack'){const waiter=acks.get(m.commandId);if(waiter){acks.delete(m.commandId);waiter.resolve(m.success===true);}else{const names={injected:'Команда отправлена',released:'Кнопка отпущена',game_not_focused_or_input_disabled:'Включи ввод на ПК и открой игру',ignition_tap_required:'Сначала отдельное короткое нажатие',input_busy:'Отпусти предыдущую кнопку',profile_mismatch:'Профиль изменён: переподключение'};text('command',names[m.code]||m.code);}if(m.code==='profile_mismatch')socket.close();}
 }catch{text('command','Ошибка данных Companion');socket.close();}};
 socket.onclose=()=>{if(ws!==socket)return;session=null;availability='';presses.clear();gestures.clear();frame=null;resetPit();text('connection','Связь потеряна · повтор…');renderLive();if(!document.hidden)retry=setTimeout(connect,2500);};socket.onerror=()=>socket.close();
 }catch{text('connection','ПК недоступен · повтор…');if(!document.hidden)retry=setTimeout(connect,2500);}finally{connecting=false;}
}
$('pairForm').onsubmit=async e=>{e.preventDefault();text('pairError','');try{const r=await fetch('/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('code').value})});if(!r.ok)throw Error('Код не принят. Получи новый код в Companion.');$('code').value='';await connect();}catch(err){text('pairError',err.message);}};
function tab(parent,label,selected,click){const b=node('button',selected?'selected':'',label);b.type='button';b.onclick=click;parent.append(b);return b;}
function attachAction(b,a){
 b.dataset.action=a.id;b.classList.add('action');if(a.gesture!=='press')b.classList.add('hold');b.oncontextmenu=e=>e.preventDefault();
 b.onpointerdown=e=>{if(b.disabled||e.button!==0)return;resetPit();const id=uid(),hold=a.gesture==='hold'||a.gesture==='tapThenHold'&&ignition;gestures.set(e.pointerId,{id,hold,a,b,time:performance.now(),x:e.clientX,y:e.clientY,cancel:false});b.setPointerCapture(e.pointerId);b.classList.add('down');if(hold){presses.set(id,a);invoke(a,'down',id);}};
 b.onpointermove=e=>{const g=gestures.get(e.pointerId);if(g&&!g.hold&&Math.hypot(e.clientX-g.x,e.clientY-g.y)>15)g.cancel=true;};
 const finish=(e,cancel)=>{const g=gestures.get(e.pointerId);if(!g)return;gestures.delete(e.pointerId);b.classList.remove('down');if(g.hold){presses.delete(g.id);invoke(a,'up',g.id);}else if(!cancel&&!g.cancel){if(a.gesture==='tapThenHold'&&performance.now()-g.time>=500)text('command','Сначала коротко нажми и отпусти, затем удерживай отдельно');else invoke(a,'press',g.id);}};
 b.onpointerup=e=>finish(e,false);b.onpointercancel=e=>finish(e,true);b.onlostpointercapture=e=>finish(e,true);b.onclick=e=>{if(e.detail===0&&a.gesture==='press'&&!b.disabled){resetPit();invoke(a,'press',uid());}};
}
function actionButton(a,label=a.label,description=a.key){const b=node('button','',undefined),s=node('span','',label),hint=node('small','',description);b.append(s,hint);attachAction(b,a);return b;}
function actionGrid(list,target=$('buttons'),labelFn){for(const a of list)target.append(actionButton(a,labelFn?labelFn(a):a.label,a.gesture==='hold'?'Удерживать · '+a.key:a.key));}
function arrows(prefix,list,target){const grid=node('div','arrows');for(const id of [null,prefix+'Up',null,prefix+'Left',prefix+'Down',prefix+'Right']){const a=id&&list.find(x=>x.id===id);if(a)grid.append(actionButton(a,{Up:'↑',Left:'←',Down:'↓',Right:'→'}[id.slice(prefix.length)],a.label));else grid.append(node('span'));}target.append(grid);}
const adjustmentDefs=[['Баланс тормозов','brakeBiasDown','brakeBiasUp'],['Дифференциал','diffDown','diffUp'],['Топливная смесь','fuelDown','fuelUp'],['Режим ERS','ersDown','ersUp']];
function adjustments(target,expandable){for(const [label,down,up] of adjustmentDefs){const pair=[action(down),action(up)].filter(Boolean);if(!pair.length)continue;if(expandable){const head=node('button','settingHead',label+(expanded===down?'  ▴':'  ▾'));head.type='button';head.onclick=()=>{release();expanded=expanded===down?'':down;renderControls();};target.append(head);}else target.append(node('h3','settingTitle',label));if(!expandable||expanded===down){const row=node('div','twoGrid');for(const a of pair)row.append(actionButton(a,a.id===down?'−':'+',a.label));target.append(row);}}}
function setPage(next,nextGroup=''){release();page=next;group=nextGroup;renderControls();}
function renderControls(){
 const f1=isF1(),pages=[...new Set(actions.map(a=>a.page))];if(f1&&!pages.includes('Трасса'))pages.push('Трасса');if(!pages.includes(page))page=pages[0]||'';
 clear($('pages'));for(const p of pages)tab($('pages'),p,p===page,()=>setPage(p));
 let groups=[...new Set(actions.filter(a=>a.page===page).map(a=>a.group||'Общие'))];if(f1&&page==='Control Scheme'&&!groups.includes('Инженер'))groups.push('Инженер');if(page==='Трасса')groups=['Карта и пилоты'];if(!groups.includes(group))group=groups[0]||'';
 clear($('groups'));if(page!=='Трасса')for(const g of groups)tab($('groups'),g,g===group,()=>{release();group=g;renderControls();});clear($('special'));clear($('buttons'));
 const visible=actions.filter(a=>a.page===page&&(a.group||'Общие')===group);
 if(f1&&page==='Трасса'){const view=node('div','raceView');view.id='raceView';$('special').append(view);renderRaceScreen();}
 else if(f1&&page==='Control Scheme'&&group==='Инженер')renderEngineer();
 else if(f1&&page==='Control Scheme'&&group==='Обзор'){arrows('look',visible,$('special'));actionGrid(visible.filter(a=>!['lookUp','lookDown','lookLeft','lookRight'].includes(a.id)));}
 else if(f1&&page==='MFD'&&group==='Навигация')renderMfdNavigation(visible);
 else if(f1&&page==='MFD'&&group==='Быстрые настройки'){adjustments($('special'),false);const ids=new Set(adjustmentDefs.flatMap(x=>x.slice(1)));actionGrid(visible.filter(a=>!ids.has(a.id)));}
 else if(f1&&page==='Menu Controls'&&group==='Навигация'){arrows('menu',visible,$('special'));actionGrid(visible.filter(a=>!['menuUp','menuDown','menuLeft','menuRight'].includes(a.id)));}
 else if(f1&&page==='Menu Controls'&&group==='Стики'){$('special').append(node('h3','settingTitle','Левый стик'));arrows('ls',visible,$('special'));$('special').append(node('h3','settingTitle','Правый стик'));arrows('rs',visible,$('special'));actionGrid(visible.filter(a=>!/^([lr]s)(Up|Down|Left|Right)$/.test(a.id)));}
 else{if(f1&&page==='Control Scheme'&&group==='Гонка'){const pit=node('button','primary wide','Пит-стоп · резина и крыло');pit.type='button';pit.onclick=()=>{page='MFD';group='Навигация';panel='mfdPit';renderControls();};$('special').append(pit);actionGrid(visible.filter(a=>a.id!=='pitStop'));$('special').append(node('p','hint','Радио инженера — T. Голосовая связь — удержание Y для микрофона ПК; звук с телефона не передаётся.'));}else actionGrid(visible);}
 renderLive();
}
function renderMfdNavigation(visible){
 const names=[['mfd','Листать'],['mfdSetup','Машина'],['mfdPit','Пит-стоп'],['mfdDamage','Повреждения'],['mfdEngine','Двигатель'],['mfdTemps','Температуры'],['map','Карта']],tabs=node('div','panelTabs');
 for(const [id,label] of names)tab(tabs,label,panel===id,()=>{release();if(id==='mfd'){const a=action(id);if(a)invoke(a);}else panel=id;renderControls();});$('special').append(tabs);
 const card=node('section','detailCard');card.id='f1Panel';$('special').append(card);renderF1Panel();
 if(panel!=='mfdPit'&&panel!=='map'&&panel!=='mfd'){const a=action(panel);if(a){const open=node('button','wide','Открыть эту страницу в игре · '+a.key);open.type='button';open.onclick=()=>{resetPit();invoke(a);};$('special').append(open);}}
 const split=node('div','mfdTools'),nav=node('div'),settings=node('div');arrows('mfd',visible,nav);adjustments(settings,true);split.append(nav,settings);$('special').append(split);
 actionGrid(visible.filter(a=>!a.id.startsWith('mfd')));
}
function currentData(){return frame&&frame.ageMs!==null&&frame.ageMs+performance.now()-frameAt<500?frame.data:null;}
function raceLive(){return !!currentData()?.f1?.race?.fresh;}
function onTrack(r=currentData()?.f1?.race){return !!r?.drivers?.some(d=>d.player&&d.result===2&&d.driverStatus!==0);}
function engineerRequests(type){if(type>=1&&type<=4)return ['В боксы на этом круге','Машина впереди','Машина позади','Обзор сессии','Напарник','Состояние болида','Моя позиция','Прогноз погоды','Топливо','Лучший круг сессии'];if(type>=15&&type<=17)return ['В боксы на этом круге','Обзор гонки','Машина впереди','Машина позади','Состояние шин','Состояние болида','Прогноз погоды','Топливо','Информация о пит-стопе'];return [];}
function renderEngineer(){const box=node('section','detailCard');$('special').append(box);const r=currentData()?.f1?.race,requests=engineerRequests(r?.sessionType);box.append(node('h2','',`Запросы инженеру · ${r?.sessionType>=15&&r?.sessionType<=17?'гонка':'тренировка'}`),node('p','hint','Запускай при закрытом радиоменю. Кнопка откроет список, выберет запрос и подтвердит его. Ответ прозвучит в игре.'));const ok=ready()&&raceLive()&&onTrack(r)&&requests.length>0;if(!ok)box.append(node('p','warning','Выйди на трассу в тренировке или гонке. В боксах запросы отключены.'));const grid=node('div','twoGrid');requests.forEach((label,i)=>{const b=node('button','',label);b.type='button';b.disabled=!ok;b.onclick=()=>runEngineer(i,label,r.sessionType);grid.append(b);});box.append(grid);}
async function runSequence(steps,waitFor,allowed){if(menuBusy||!allowed())return false;menuBusy=true;renderLive();let ok=true;for(let i=0;i<steps.length;i++){if(!allowed()||!await invokeAck(steps[i])){ok=false;break;}await sleep(waitFor(i));}menuBusy=false;renderLive();return ok&&allowed();}
async function runEngineer(index,label,type){const requests=engineerRequests(type);if(index<0||index>=requests.length)return;const allowed=()=>inputReady()&&currentData()?.f1?.race?.sessionType===type&&raceLive()&&onTrack();const steps=['radio',...Array(index).fill('mfdDown'),'mfdRight'];const ok=await runSequence(steps,i=>i===0?1400:300,allowed);text('command',ok?`Запрос отправлен: ${label}. Проверь ответ в игре.`:'Запрос остановлен: проверь ввод и закрытое радиоменю.');renderControls();}
function pitReady(){const d=currentData(),r=d?.f1?.race;return inputReady()&&d?.f1?.mfdPanelIndex===1&&r?.fresh&&r.sessionType>=15&&r.sessionType<=17&&onTrack(r);}
function pitSteps(from,to,increase){const delta=(to-from+3)%3,nav=delta===1?['mfdDown']:delta===2?['mfdUp']:[];return [...nav,increase?'mfdRight':'mfdLeft'];}
function pitSelectionSteps(from,row,current,target,count){if(current<0||current>=count||target<0||target>=count)return[];const navigation=pitSteps(from,row,true).slice(0,-1);return [...navigation,...Array(Math.abs(target-current)).fill(target>current?'mfdRight':'mfdLeft')];}
async function runPit(row,steps,selected){const ok=await runSequence(steps,()=>320,pitReady);if(ok){pitCursor=row;if(row===1)pitRepair=selected;if(row===2)pitTyre=selected;pitSent=true;text('command','Выбор отправлен. Шины и ремонт проверь в MFD; крыло подтверждается телеметрией.');}else{resetPit();text('command','Остановлено: заново открой пит-меню и сверь исходные значения.');}renderF1Panel();}
function pitAdjust(increase){if(pitCursor!==null)runPit(0,pitSteps(pitCursor,0,increase));}
function pitSelect(row,value){const current=row===1?pitRepair:pitTyre,count=row===1?3:5;if(pitCursor!==null&&current!==null)runPit(row,pitSelectionSteps(pitCursor,row,current,value,count),value);}
const tyreNames=['Soft','Medium','Hard','Inter','Full Wet'],tyreLetters=['S','M','H','I','W'],tyreColors=['#ff646b','#ffd85a','#f2f4f5','#55d394','#53abff'],repairNames=['Авто','Да','Нет'];
function tyreButton(i,selected,enabled,click){const b=node('button','tyre'+(selected?' selectedTyre':''));b.type='button';b.disabled=!enabled;b.style.setProperty('--tyre',tyreColors[i]);b.append(node('strong','',tyreLetters[i]),node('small','',tyreNames[i]));b.onclick=click;return b;}
function openSync(){syncChoice={row:null,tyre:null,repair:null};renderSync();$('pitSync').showModal();}
function renderSync(){const add=(id,items,key,tyres=false)=>{const root=$(id);clear(root);items.forEach((label,i)=>{const b=tyres?tyreButton(i,syncChoice[key]===i,true,()=>{syncChoice[key]=i;renderSync();}):node('button',syncChoice[key]===i?'selected':'',label);b.type='button';if(!tyres)b.onclick=()=>{syncChoice[key]=i;renderSync();};root.append(b);});};add('syncRows',['Крыло','Ремонт','Шины'],'row');add('syncTyres',tyreNames,'tyre',true);add('syncRepair',repairNames,'repair');$('syncConfirm').disabled=!pitReady()||Object.values(syncChoice).some(v=>v===null);}
$('syncConfirm').onclick=e=>{if($('syncConfirm').disabled){e.preventDefault();return;}pitCursor=syncChoice.row;pitTyre=syncChoice.tyre;pitRepair=syncChoice.repair;pitSent=false;text('command','Исходные значения записаны. После изменения MFD геймпадом сверь их заново.');$('pitSync').close();renderF1Panel();};
function fmt(v,unit='',dec=0){return Number.isFinite(v)?Number(v).toFixed(dec)+unit:'—';}
function compound(v){return({16:'Soft',20:'Soft',17:'Medium',21:'Medium',18:'Hard',22:'Hard',19:'Super Soft',7:'Intermediate',8:'Wet',15:'Wet'})[v]||(v==null?'—':'Состав '+v);}
function metricGrid(target,values,fields,unit=''){const grid=node('div','metrics');for(const [key,label] of fields){const item=node('div','metric');item.append(node('small','',label),node('strong','',fmt(values[key],unit)));grid.append(item);}target.append(grid);}
function renderF1Panel(){const root=$('f1Panel');if(!root)return;clear(root);const d=currentData()?.f1,v=d?.values||{};const titles={mfdPit:'ПИТ-СТОП',mfdDamage:'ШИНЫ И ПОВРЕЖДЕНИЯ',mfdEngine:'ДВИГАТЕЛЬ',mfdTemps:'ТЕМПЕРАТУРЫ И ДАВЛЕНИЕ',map:'КАРТА ТРАССЫ',mfdSetup:'СОСТОЯНИЕ БОЛИДА'};root.append(node('h2','',titles[panel]||'MFD'));
 if(panel==='map'){const canvas=node('canvas','circuit');canvas.id='panelMap';root.append(canvas,node('p','mapStatus',''));drawCircuit(canvas,currentData()?.f1?.race,false);return;}
 if(!d)root.append(node('p','warning','Нет свежих данных F1. На трассе включи UDP → ПК, порт 20777.'));
 if(panel==='mfdPit'){renderPit(root,d,v);return;}
 if(panel==='mfdDamage'||panel==='mfdTemps'){root.append(node('p','lead',`${compound(v.compound)} · возраст ${fmt(v.tyreAge,' круг.')}`));const grid=node('div','wheelGrid');[[2,'Передняя левая'],[3,'Передняя правая'],[0,'Задняя левая'],[1,'Задняя правая']].forEach(([i,name])=>{const w=d?.wheels?.[i],card=node('div','wheel');card.append(node('small','',name),node('strong','',panel==='mfdDamage'?`Износ ${fmt(w?.wear,'%',1)}`:`${fmt(w?.surface,' °C')} / ${fmt(w?.inner,' °C')}`),node('small','',panel==='mfdDamage'?`Повреждение ${fmt(w?.damage,'%')}`:'Поверхность / внутри'),node('small','',`${fmt(w?.pressure,' psi',1)} · тормоз ${fmt(w?.brake,' °C')}`));grid.append(card);});root.append(grid);if(panel==='mfdDamage')metricGrid(root,v,[['frontLeftWingDamage','Переднее крыло Л'],['frontRightWingDamage','Переднее крыло П'],['rearWingDamage','Заднее крыло'],['floorDamage','Днище']],'%');}
 else if(panel==='mfdEngine'){root.append(node('p','bigValue','Охлаждение '+fmt(d?.engineTemperature,' °C')));metricGrid(root,v,[['engineDamage','Повреждение двигателя'],['gearboxDamage','Коробка'],['iceWear','Износ ICE'],['mguHWear','MGU-H'],['mguKWear','MGU-K'],['tcWear','Турбина'],['esWear','Батарея'],['ceWear','Электроника']],'%');root.append(node('p','lead','Энергия ERS '+fmt(Number.isFinite(v.ersEnergy)?v.ersEnergy/1000000:null,' МДж',2)));}
 else{root.append(node('p','bigValue',`${compound(v.compound)} · ${fmt(v.tyreAge,' круг.')}`));metricGrid(root,v,[['frontWing','Переднее крыло'],['rearWing','Заднее крыло'],['brakeBias','Баланс тормозов, %'],['differential','Дифференциал, %'],['fuelMix','Топливная смесь'],['ersMode','Режим ERS']]);root.append(node('p','lead',`Трасса ${fmt(v.trackTemperature,' °C')} · воздух ${fmt(v.airTemperature,' °C')}`));}
 if(d)root.append(node('p','hint','— означает, что соответствующий пакет ещё не получен или устарел.'));
}
function renderPit(root,d,v){root.append(node('p','lead','Подготовка следующего пит-стопа · доступна на трассе'),node('p','bigValue',`Сейчас: ${compound(v.compound)} · ${fmt(v.tyreAge,' круг.')}`));const open=node('button','wide','Открыть пит-меню в игре · F2');open.disabled=!session||menuBusy;open.onclick=()=>{resetPit();const a=action('mfdPit');if(a)invoke(a);renderF1Panel();};const sync=node('button','wide',pitCursor===null?'Сверить исходные значения с MFD':'Повторно сверить с MFD');sync.disabled=!pitReady();sync.onclick=openSync;root.append(open,sync);if(!pitReady())root.append(node('p','warning','Открой игровую страницу пит-стопа в гонке. При потере связи команды временно отключены.'));if(pitCursor===null)root.append(node('p','hint','Перед первым выбором укажи выделенную строку и значения из игры. После изменения геймпадом сверь их заново.'));
 root.append(node('h3','settingTitle','1. Угол переднего крыла'));const wing=node('div','pitRow'),desc=node('div');desc.append(node('strong','bigValue','На пит-стопе: '+fmt(v.nextFrontWing)),node('small','',`Сейчас на машине: ${fmt(v.frontWing)}`));wing.append(desc);for(const [label,inc] of [['−',false],['+',true]]){const b=node('button','square',label);b.disabled=!pitReady()||pitCursor===null;b.onclick=()=>pitAdjust(inc);wing.append(b);}root.append(wing);
 root.append(node('h3','settingTitle','2. Замена переднего крыла'),node('p','hint',(pitSent?'Отправлен выбор: ':'Указано при сверке: ')+(pitRepair===null?'—':repairNames[pitRepair])));const repairs=node('div','threeGrid');[1,2,0].forEach(i=>{const b=node('button',pitRepair===i?'selected':'',repairNames[i]);b.disabled=!pitReady()||pitCursor===null;b.onclick=()=>pitSelect(1,i);repairs.append(b);});root.append(repairs);
 root.append(node('h3','settingTitle','3. Следующие шины'),node('p','hint',(pitSent?'Отправлен выбор: ':'Указано при сверке: ')+(pitTyre===null?'—':tyreNames[pitTyre])));const tyres=node('div','tyreGrid'),f1Tyres=[16,17,18,7,8].includes(v.compound);tyreNames.forEach((_,i)=>tyres.append(tyreButton(i,pitTyre===i,pitReady()&&pitCursor!==null&&f1Tyres,()=>pitSelect(2,i))));root.append(tyres);if(!f1Tyres)root.append(node('p','hint','Пять составов доступны для болидов F1. Для F2 набор шин отличается.'));root.append(node('p','hint','Шины и ремонт по UDP не подтверждаются: подсветка показывает выбор с телефона. Сверяй результат в MFD.'));
}
const teamColors=['#27f4d2','#e95a62','#7298ff','#64c4ff','#2ab6a0','#ff87bc','#9da5ff','#dbdee2','#ffa23d','#75ee58'];
function teamColor(team){return teamColors[team]||['#74cce0','#ffc869','#b7a3ed','#b6d881'][Math.abs(team||0)%4];}
function shortName(d){const p=(d.name||'').trim().split(/\s+/).pop()||('#'+d.number);return p.slice(0,3).toUpperCase();}
function onTrackDriver(d){return d.result===2&&d.driverStatus!==0;}
function pointAt(track,distance,trackLength){if(!Number.isFinite(distance)||trackLength<=0||track.points.length<2)return null;let sums=[0],total=0;for(let i=1;i<track.points.length;i++){total+=Math.hypot(track.points[i][0]-track.points[i-1][0],track.points[i][1]-track.points[i-1][1]);sums.push(total);}if(total<=0)return null;const fraction=((distance%trackLength)+trackLength)%trackLength/trackLength,along=fraction*total;let i=sums.findIndex(x=>x>along);if(i<1)i=1;const span=sums[i]-sums[i-1],t=span?((along-sums[i-1])/span):0,a=track.points[i-1],b=track.points[i];return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t];}
function drawCircuit(canvas,race,compact){const status=canvas.nextElementSibling,track=circuits.get(race?.trackId);if(!track){if(status)status.textContent=!race||race.trackId<0?'Ожидание названия трассы от игры':'Для этой конфигурации схема пока не добавлена';return;}const box=canvas.getBoundingClientRect(),w=Math.max(280,box.width),h=compact?100:260,dpr=Math.min(2,devicePixelRatio||1);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.height=h+'px';const c=canvas.getContext('2d');c.scale(dpr,dpr);const xs=track.points.map(p=>p[0]),ys=track.points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),margin=compact?12:28,rotate=(maxY-minY)>(maxX-minX)&&w>h,ex=rotate?maxY-minY:maxX-minX,ey=rotate?maxX-minX:maxY-minY,scale=Math.min((w-margin*2)/Math.max(1,ex),(h-margin*2)/Math.max(1,ey));const project=p=>{const x=p[0]-(minX+maxX)/2,y=p[1]-(minY+maxY)/2;return[w/2+(rotate?y:x)*scale,h/2+(rotate?-x:y)*scale];};c.lineJoin='round';c.beginPath();track.points.forEach((p,i)=>{const [x,y]=project(p);i?c.lineTo(x,y):c.moveTo(x,y);});c.strokeStyle='#304653';c.lineWidth=compact?6:10;c.stroke();c.strokeStyle='#a5b9c5';c.lineWidth=compact?2:3;c.stroke();const [sx,sy]=project(track.points[0]);c.fillStyle='#fff';c.fillRect(sx-3,sy-3,6,6);const live=race?.fresh,markers=live?race.drivers.filter(onTrackDriver):[];markers.sort((a,b)=>Number(a.player)-Number(b.player));for(const d of markers){const p=pointAt(track,d.distance,race.trackLength);if(!p)continue;const [x,y]=project(p),r=compact?3:5;c.beginPath();c.arc(x,y,r+2,0,Math.PI*2);c.fillStyle=d.player?'white':'#0b1115';c.fill();c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=teamColor(d.team);c.fill();if(!compact){const label=(d.position>0?d.position:'—')+' '+shortName(d);c.font='bold 11px system-ui';const tw=c.measureText(label).width+8,lx=Math.min(w-tw,Math.max(0,x+9)),ly=Math.min(h-18,Math.max(0,y-8));c.fillStyle='rgba(16,32,41,.93)';c.fillRect(lx,ly,tw,17);c.fillStyle='white';c.fillText(label,lx+4,ly+12);}}if(status)status.textContent=`${track.name} · ${!live?'схема готова, ждём пилотов':markers.length?markers.length+' на трассе · вы с белым ободком':'пилоты в боксах'}`;}
function renderRaceScreen(){const root=$('raceView');if(!root)return;clear(root);const race=currentData()?.f1?.race,layout=node('div','raceLayout'),map=node('section','detailCard'),canvas=node('canvas','circuit');map.append(node('h2','',circuits.get(race?.trackId)?.name||'Карта трассы'),canvas,node('p','mapStatus',''));const list=node('section','detailCard');list.append(node('h2','','ПОРЯДОК ПИЛОТОВ'),node('p','hint',race?.fresh?`Позиции из игры · ${race.drivers.length} машин`:'Ожидание свежих позиций'));const rows=node('div','driverList');for(const d of race?.drivers||[]){const status=!race.fresh?'—':d.result===7||d.result===4?'DNF':d.result===5?'DSQ':d.result===3?'ФИНИШ':d.pit>0?'PIT':'Кр. '+d.lap,row=node('div','driver'+(d.player?' player':''));const pos=node('span','position',race.fresh&&d.position>0?String(d.position):'—'),info=node('div');const name=node('strong','',(d.player?'ВЫ · ':'')+d.name);name.style.color=teamColor(d.team);info.append(name,node('small','',`${shortName(d)} · #${d.number} · ${status}`));row.append(pos,info);rows.append(row);}if(!race?.drivers?.length)rows.append(node('p','hint','Список появится после пакета участников. В гонке на время полной решётки нет.'));list.append(rows);layout.append(map,list);root.append(layout);drawCircuit(canvas,race,false);if(race?.fresh){const sorted=race.drivers,idx=sorted.findIndex(d=>d.player);if(idx>=0){const me=sorted[idx],ahead=sorted[idx-1],behind=sorted[idx+1];root.append(node('p','lead',`Впереди: ${ahead?.name||'вы лидер'} · Позади: ${behind?.name||'—'}`));if(race.sessionType>=15&&race.sessionType<=17&&me.position>1&&me.gapAheadMs>0)root.append(node('p','lead',`До машины впереди: ${(me.gapAheadMs/1000).toFixed(3)} с`));}}root.append(node('p','hint','Положение по дистанции круга приблизительное. Схемы: f1-circuits · © Tomislav Bacinger · MIT.'));}
function renderDetails(force=false){if(!isF1())return;if(force||performance.now()-lastDetails>=500){lastDetails=performance.now();renderF1Panel();renderRaceScreen();}}
function renderLive(){const d=currentData();text('live',frame?.source==='demo'?'ДЕМОНСТРАЦИЯ':d?'● LIVE':'Нет свежих данных');text('rpm',d?Math.round(d.rpm)+' RPM':'— RPM');$('rpmBar').value=d&&d.maxRpm?Math.min(1,d.rpm/d.maxRpm):0;text('gear',d?.gearDisplay??'—');text('speed',d?Math.round(d.speedMps*3.6):'—');text('fuel','Топливо: '+(d?.fuelFraction!=null?Math.round(d.fuelFraction*100)+'%':'—'));text('inputState',menuBusy?'Выполняется последовательность…':({ready:'Ввод готов',disabled:'Разреши клавиатурный ввод на ПК',unfocused:'Вернись в окно игры на ПК',demo:'Демонстрация · ввод отключён'})[availability]||'Ожидание подключения');
 for(const b of document.querySelectorAll('.action')){const a=action(b.dataset.action);b.disabled=!ready();b.classList.toggle('on',d?.actionStates?.[a?.id]===true);b.classList.toggle('low',a?.id==='lights'&&d?.headlights===1);b.classList.toggle('high',a?.id==='lights'&&d?.headlights===2);const hint=b.querySelector('small');if(hint&&a)hint.textContent=a.gesture==='tapThenHold'?(ignition?'Теперь удерживай: запуск':'Коротко: зажигание'):a.gesture==='hold'?'Удерживать · '+a.key:a.key;}
 const f=d?.f1;$('wheelsPanel').hidden=!isF1();clear($('wheels'));for(const [i,name] of [[2,'Переднее левое'],[3,'Переднее правое'],[0,'Заднее левое'],[1,'Заднее правое']]){const w=f?.wheels?.[i],item=node('div','wheel');item.append(node('small','',name),node('strong','',w?w.surface+' °C':'—'),node('small','',`Износ ${w?.wear!=null?Math.round(w.wear)+'%':'—'} · ${w?Number(w.pressure).toFixed(1)+' PSI':'—'}`));$('wheels').append(item);}text('engine','Двигатель: '+(f?f.engineTemperature+' °C':'—'));$('racePanel').hidden=true;renderDetails();}
setInterval(()=>{if(session&&!document.hidden){send('input.renew',{pressIds:[...presses.keys()]});if(performance.now()-lastMessage>10000)ws?.close();}renderLive();},100);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else connect();});window.addEventListener('pagehide',stop);window.addEventListener('blur',release);window.addEventListener('resize',()=>renderDetails(true));window.addEventListener('pageshow',()=>{if(!ws&&!document.hidden)connect();});connect();
