"use strict";
let beamLabels={zones:{FL:'Спереди слева',FR:'Спереди справа',ML:'Слева по центру',MR:'Справа по центру',RL:'Сзади слева',RR:'Сзади справа'},faults:{}};
fetch('/beamng-damage-ui.json').then(r=>r.json()).then(v=>{beamLabels=v;const root=document.getElementById('beamNgDamage');if(root)root.dataset.snapshot='';}).catch(()=>{});
let beamTab='Кузов';
function mountBeamNgDamage(root){
 const panel=node('section','beamDamage');panel.id='beamNgDamage';const layout=node('div','beamDamageLayout'),scene=node('section','card'),details=node('section','card');scene.classList.add('beamScene');details.classList.add('beamDetails');
 scene.append(node('h2','','ДИАГНОСТИКА МАШИНЫ'),node('h3','beamName'),node('p','hint beamClass'),node('div','beamPicture'),node('p','hint','Зоны кузова: зелёный 0–5%, жёлтый 6–30%, красный >30%. Колесо: красный — поломка, жёлтый — спущена шина.'));
 const tabs=node('nav','beamTabs');for(const name of ['Кузов','Колёса','Узлы','Детали']){const b=node('button','',name);b.type='button';b.dataset.beamTab=name;b.onclick=()=>{beamTab=name;panel.dataset.snapshot='';updateBeamNgDamage(displayData());};tabs.append(b);}details.append(tabs,node('div','beamContent'));layout.append(scene,details);panel.append(layout);root.append(panel);
 const strip=node('div','referenceReadouts');for(const[label,key]of [['КМ/Ч','speed'],['ПЕРЕДАЧА','gear'],['RPM','rpm'],['ТОПЛИВО','fuel']])strip.append(dashboardMetric(label,key));root.append(strip);
 root.append(dashboardButtons([['ignition','Зажигание'],['lights','Фары'],['hazards','Аварийка'],['recoverRoad','На дорогу']],'referenceQuickBar'));return true;
}
function updateBeamNgDamage(data){
 const panel=document.getElementById('beamNgDamage');if(!panel||profileId!=='beamng-default')return;
 const identity=data?.vehicle||lastKnownVehicle,v=identity?.controlled===false?null:identity,damage=v?data?.beamNg:null,signature=JSON.stringify([identity,damage,beamTab,!!currentData(),beamLabels]);if(panel.dataset.snapshot===signature)return;panel.dataset.snapshot=signature;
 panel.querySelector('.beamName').textContent=v?.name||(identity?.controlled===false?'Вы не в технике':'Ждём данные машины');panel.querySelector('.beamClass').textContent=v?`${vehicleLabels[v.kind]||'Неизвестный класс'} · ${vehicleAxles(vehicleWheels(v.wheels))||'—'} оси · ${currentData()?'живые данные':'последние показания'}`:'Нужен мод BeamNG 0.4.0';
 const picture=panel.querySelector('.beamPicture');picture.replaceChildren();if(v){const svg=vehicleSvg(v.kind,[]);picture.append(svg);const rect=roadRect(v.kind);
  const drawing=beamLabels.drawing?.[v.kind];
  if(rect&&damage&&drawing){const bw=290*rect[2]/rect[3];
   for(const zone of drawing.zones){const value=damage.body?.[zone.key];if(!Number.isFinite(value))continue;const e=vElement(svg,'path',{d:zone.path,transform:`translate(${160-bw/2} 0) scale(${bw/1000} .29)`,fill:f1DamageColor(value*100),'fill-opacity':value>.05?.18:.015,stroke:f1DamageColor(value*100),'stroke-opacity':value>.05?.85:.28,'stroke-width':.9,'vector-effect':'non-scaling-stroke'});e.dataset.beamZone=zone.key;e.dataset.value=String(value);}
   const wheels=vehicleWheels(v.wheels),shape=drawing.wheel;if(wheels.length){const min=Math.min(...wheels.map(w=>w.z)),span=Math.max(1,Math.max(...wheels.map(w=>w.z))-min),half=Math.max(.5,...wheels.map(w=>Math.abs(w.x)));for(const wd of damage.wheels||[]){const w=wheels[wd.index];if(!w||![wd.broken,wd.flat,wd.brakeDamaged].some(v=>typeof v==='boolean'))continue;const bad=wd.broken||wd.brakeDamaged||wd.flat,color=wd.broken||wd.brakeDamaged?'#ff575d':wd.flat?'#ffc449':'#7dda71',tw=bw*shape.width,th=290*shape.height,x=160+w.x/half*bw*shape.side,y=290*(shape.front+(w.z-min)/span*(shape.rear-shape.front)),l=x-tw/2,r=x+tw/2,t=y-th/2,b=y+th/2,cr=tw*.45;const e=vElement(svg,'path',{d:`M${l} ${t+cr}Q${l} ${t} ${l+cr} ${t}H${r-cr}Q${r} ${t} ${r} ${t+cr}V${b-cr}Q${r} ${b} ${r-cr} ${b}H${l+cr}Q${l} ${b} ${l} ${b-cr}Z`,fill:color,'fill-opacity':bad?.20:.035,stroke:color,'stroke-opacity':bad?.95:.45,'stroke-width':1});e.dataset.beamWheel=wd.index;}}

  }
 }
 panel.querySelectorAll('[data-beam-tab]').forEach(b=>b.classList.toggle('active',b.dataset.beamTab===beamTab));
 const content=panel.querySelector('.beamContent');content.replaceChildren();const add=(tag,text,cls='')=>{const e=node(tag,cls,text);content.append(e);return e;};const row=(name,value,color)=>{const e=add('div','','beamRow');e.append(node('span','',name));const n=node('strong','',value);if(color)n.style.color=color;e.append(n);};
 if(!damage){add('p','Данные диагностики не поступили. Обновите мод BeamNG до 0.4.0 и перезагрузите машину Ctrl+R.','hint');return;}
 if(beamTab==='Кузов'){for(const [key,name]of Object.entries(beamLabels.zones)){const x=damage.body?.[key];row(name,Number.isFinite(x)?fmt(x*100,'%'):'—',f1DamageColor(Number.isFinite(x)?x*100:null));}add('p','Степень повреждения связей кузова по шести зонам. Это не процент стоимости ремонта.','hint');}
 else if(beamTab==='Колёса'){if(!damage.wheels?.length)add('p','Состояния колёс не переданы','hint');for(const w of damage.wheels||[]){add('h3',w.name||'Колесо '+(w.index+1));for(const [name,key]of [['Колесо / крепление','broken'],['Шина','flat'],['Тормоз','brakeDamaged']]){const bad=w[key];row(name,bad===true?name==='Шина'?'Спущена':'Повреждено':bad===false?'Без отметки повреждения':'Нет данных',bad===true?'#ff575d':bad===false?'#7dda71':'#abbdc7');}add('p','Тормоз '+fmt(w.brakeTemperature,' °C'),'hint');}}
 else if(beamTab==='Узлы'){add('p','Охлаждение '+fmt(damage.coolantTemperature,' °C')+' · Масло '+fmt(damage.oilTemperature,' °C'));for(const[key,name]of Object.entries(beamLabels.faults).sort(([a],[b])=>Number(damage.faults?.[b]===true)-Number(damage.faults?.[a]===true))){const bad=damage.faults?.[key];row(name,bad===true?'ЕСТЬ':bad===false?'НЕТ':'—',bad===true?'#ff575d':bad===false?'#7dda71':'#abbdc7');}add('p','Статусы отмеченных игрой неисправностей. Прочерк означает недоступное состояние или оборудование.','hint');}
 else{add('p',Number.isFinite(damage.totalDamagedParts)?`Деталей с повреждениями: ${damage.totalDamagedParts} · показано ${damage.parts?.length||0}`:'Данные деталей не переданы');for(const p of damage.parts||[]){row(p.name,'Оценка '+fmt(p.damage*100,'%'),f1DamageColor(p.damage*100));}if(damage.totalDamagedParts===0)add('p','Игра не отметила повреждённых деталей');add('p','До восьми наиболее повреждённых деталей по оценке BeamNG. Учитываются разрыв и деформация связей.','hint');}
}
