"""Generate the three clients and Lua category registry from one reviewed manifest.
Run again after changing assets/fs25-equipment.json. No game assets are copied.
"""
import json
import re
import struct
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
data = json.loads((root/'assets/fs25-equipment.json').read_text(encoding='utf-8'))
kinds = data['kinds']
assert len(kinds) == len(set(kinds))
assert all(v in kinds for v in data['categories'].values())
assert all(re.fullmatch(r'[a-z]+', k) for k in kinds)
for atlas, dimensions in data['atlases'].items():
    assert re.fullmatch(r'fs25-flat-[1-6]', atlas)
    png=(root/f'assets/vehicles/{atlas}.png').read_bytes()
    assert png[:8]==b'\x89PNG\r\n\x1a\n'
    assert list(struct.unpack('>II',png[16:24]))==dimensions
for info in kinds.values():
    x,y,w,h=info['rect']; width,height=data['atlases'][info['atlas']]
    assert x>=0 and y>=0 and w>0 and h>0 and x+w<=width and y+h<=height
def write(path, text):
    if '--check' in sys.argv:
        assert path.read_text(encoding='utf-8')==text, f'Regenerate {path.relative_to(root)}'
    else:
        path.write_text(text,encoding='utf-8')
q = lambda x: json.dumps(x, ensure_ascii=False)

cs = '// Generated by tools/qa/generate-fs25-registry.py; edit assets/fs25-equipment.json.\nnamespace SimDeck.Core;\ninternal static class Fs25EquipmentRegistry {\n'
cs += 'internal static readonly IReadOnlyDictionary<string,string> Labels = new Dictionary<string,string> {\n'
cs += ',\n'.join(f'[{q(k)}]={q(v["label"])}' for k,v in kinds.items())+'\n};\n}\n'
write(root/'companion/SimDeck.Core/Fs25EquipmentRegistry.cs',cs)

kt = '// Generated by tools/qa/generate-fs25-registry.py; edit assets/fs25-equipment.json.\npackage dev.simdeck\n'
kt += 'internal val fs25EquipmentLabels=mapOf(\n'+',\n'.join(f'{q(k)} to {q(v["label"])}' for k,v in kinds.items())+'\n)\n'
kt += 'internal val fs25EquipmentSprites=mapOf(\n'+',\n'.join(f'{q(k)} to VehicleSprite({q(v["atlas"])},{",".join(map(str,v["rect"]))})' for k,v in kinds.items())+'\n)\n'
write(root/'android/app/src/main/java/dev/simdeck/Fs25EquipmentRegistry.kt',kt)

js = '// Generated by tools/qa/generate-fs25-registry.py; edit assets/fs25-equipment.json.\n'
js += 'const fs25EquipmentLabels='+q({k:v['label'] for k,v in kinds.items()})+';\n'
js += 'const fs25EquipmentSprites='+q({k:[v['atlas'],v['rect']] for k,v in kinds.items()})+';\n'
js += 'const fs25AtlasSizes='+q(data['atlases'])+';\n'
write(root/'companion/SimDeck.App/Browser/fs25-equipment.js',js)

lua = '-- Generated by tools/qa/generate-fs25-registry.py; edit assets/fs25-equipment.json.\nSimDeckEquipmentCategories = {\n'
lua += ',\n'.join(f'[{q(k.lower())}]={q(v)}' for k,v in sorted(data['categories'].items()))+'\n}\n'
write(root/'mods/FS25_SimDeckStatus/EquipmentCategories.lua',lua)
print(f'Generated {len(kinds)} illustrated classes and {len(data["categories"])} category mappings.')
